spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: test
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  security:
    user:
      name: test
      password: test
server:
  port: 9090
